ALTER TABLE "GitHubConnection" ADD COLUMN "githubUserId" BIGINT;
ALTER TABLE "GitHubConnection" ADD COLUMN "username" TEXT;
ALTER TABLE "GitHubConnection" ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "PullRequest" ADD COLUMN "htmlUrl" TEXT;
ALTER TABLE "PullRequest" ADD COLUMN "description" TEXT;
ALTER TABLE "PullRequest" ADD COLUMN "ciStatus" TEXT NOT NULL DEFAULT 'UNKNOWN';
ALTER TABLE "PullRequest" ADD COLUMN "reviewStatus" TEXT NOT NULL DEFAULT 'NONE';
